services:
  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile.flink
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile.flink
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 6
  
  dev-environment:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8888:8888"  # For Jupyter Notebook if needed
    depends_on:
      - jobmanager
      - taskmanager
    environment:
      - FLINK_JOB_MANAGER_HOST=jobmanager
      - FLINK_JOB_MANAGER_PORT=6124

volumes:
  flink-checkpoints:

networks:
  default:
    name: roadrunner-network
    external: true