services:
  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile.flink
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///flink-checkpoints
      - PYTHON_PATH=/opt/venv/bin/python
      - PYTHONPATH=/opt/flink/opt/python
    volumes:
      - ./flink-checkpoints:/flink-checkpoints

  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile.flink
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        state.backend: filesystem
        state.checkpoints.dir: file:///flink-checkpoints
      - PYTHON_PATH=/opt/venv/bin/python
      - PYTHONPATH=/opt/flink/opt/python
    volumes:
      - ./flink-checkpoints:/flink-checkpoints

  dev-environment:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8888:8888"  # For Jupyter Notebook if needed
    depends_on:
      - jobmanager
      - taskmanager
    environment:
      - FLINK_JOB_MANAGER_HOST=jobmanager
      - FLINK_JOB_MANAGER_PORT=6123
      - PYTHONPATH=/app:/opt/flink/opt/python
      - PYTHON_PATH=/opt/venv/bin/python

networks:
  default:
    name: roadrunner-network
    external: true